db.ventas2.insertMany([
    {"id_venta": 1,
    "nombre_producto": "disco5KG",
    "precio_unitario_coste": 5.20,
    "precio_unitario_venta": 7.90,
    "fecha_venta": ISODate("2020-04-01T08:00:00Z"),
    "unidades": 20,
    "cliente": "FitnesScola",
    "vendedor": "Manolo Gutierrez",},

    {"id_venta": 2,
    "nombre_producto": "pack_mancuernas20KG",
    "precio_unitario_coste": 22,
    "precio_unitario_venta": 28.90,
    "fecha_venta": ISODate("2020-03-10T08:00:00Z"),
    "unidades": 4,
    "cliente": "GymEuroSport",
    "vendedor": "Jose Diaz",},

    {"id_venta": 3,
    "nombre_producto": "disco10KG",
    "precio_unitario_coste": 9,
    "precio_unitario_venta": 12.90,
    "fecha_venta": ISODate("2020-02-21T08:00:00Z"),
    "unidades": 18,
    "cliente": "FitnesScola",
    "vendedor": "Diego Hernández",},

    {"id_venta": 4,
    "nombre_producto": "disco10KG",
    "precio_unitario_coste": 9,
    "precio_unitario_venta": 12.90,
    "fecha_venta": ISODate("2020-01-19T08:00:00Z"),
    "unidades": 29,
    "cliente": "AreaFit",
    "vendedor": "Manolo Gutierrez",},

    {"id_venta": 5,
    "nombre_producto": "barra_Z10KG",
    "precio_unitario_coste": 37,
    "precio_unitario_venta": 45.90,
    "fecha_venta": ISODate("2019-11-21T08:00:00Z"),
    "unidades": 4,
    "cliente": "BullFitLife",
    "vendedor": "Antonio Moreira",},

    {"id_venta": 6,
    "nombre_producto": "disco10KG",
    "precio_unitario_coste": 9,
    "precio_unitario_venta": 12.90,
    "fecha_venta": ISODate("2020-05-11T08:00:00Z"),
    "unidades": 18,
    "cliente": "FitnesScola",
    "vendedor": "Diego Hernández",},

    {"id_venta": 7,
    "nombre_producto": "banco_abdominales",
    "precio_unitario_coste": 52,
    "precio_unitario_venta": 78.90,
    "fecha_venta": ISODate("2020-02-21T08:00:00Z"),
    "unidades": 3,
    "cliente": "AreaFit",
    "vendedor": "Antonio Moreira",},

    {"id_venta": 8,
    "nombre_producto": "disco10KG",
    "precio_unitario_coste": 9,
    "precio_unitario_venta": 12.90,
    "fecha_venta": ISODate("2019-10-15T08:00:00Z"),
    "unidades": 40,
    "cliente": "MCfit",
    "vendedor": "Alejandro Gómez",},

    {"id_venta": 9,
    "nombre_producto": "barra_Z10KG",
    "precio_unitario_coste": 37,
    "precio_unitario_venta": 45.90,
    "fecha_venta": ISODate("2019-10-16T08:00:00Z"),
    "unidades": 7,
    "cliente": "MCfit",
    "vendedor": "Alejandro Gómez",},

    {"id_venta": 10,
    "nombre_producto": "barra_20KG",
    "precio_unitario_coste": 55,
    "precio_unitario_venta": 69.90,
    "fecha_venta": ISODate("2020-06-16T08:00:00Z"),
    "unidades": 5,
    "cliente": "SevillaFit",
    "vendedor": "David Sánchez",}
])